### ISSUE TITLE
mac

### ISSUE THREAD

**Issue by amatii** [blackliner/automata#1]
I am trying to build the example for opencv with "bazel build //opencv:opencv" on Mac.
But I am getting this error:

INFO: Analyzed target //opencv:opencv (4 packages loaded, 41 targets configured).
INFO: Found 1 target...
ERROR: /Users/me/Documents/Project/test/automata/BUILD:3:15: error executing shell command: '/bin/bash -c #!/usr/bin/env bash
function cleanup_function() {
local ecode=$?
if [ $ecode -eq 0 ]; then
cleanup_on_success
else
cleanup_on_failure
fi
}
set -e
function cleanup_on_success() {
printf...' failed: I/O exception during sandboxed execution: /System/Volumes/Data/home/fberchtold (No such file or directory)
Target //opencv:opencv failed to build

**Comment by blackliner** [comment]
Thanks for trying it out. The problem was some customization for ccache. https://github.com/blackliner/automata/commit/0f8d391773e4a3cc28c8f1a156d62e071ed6ed8a fixed it.
